version: '2.0'
services:
  mongo_arb:
    image: 'mongo:3.6-xenial'
    container_name: 'mongo_arb'
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  arb:
    container_name: 'arb'
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    volumes:
      - /usr/src/app/arb/node_modules
      - ./:/usr/src/app/arb
    environment:
      NODE_ENV: development
    depends_on:
      - mongo_arb
    links:
      - mongo_arb